### ISSUE TITLE
Your conclusion?

### ISSUE THREAD

**Issue by hs115488** [kelbahloul/Python-Data-Analysis-Projects-#2]
What are you trying to prove? Is LLY a good buy? Is it worth it? How is worth it? What are the products that make it worth it?

**Comment by kelbahloul** [comment]
Based on historical data and the markets trend, I believe it is a good buy for investors. First, LLY is one of the biggest pharmaceutical corporations, so healthcare is a major sector of our economy. The products they produce, such as insulin and prescription drugs. Investors would be flooding the stock with hedge funds. Yes, every company is like that. I believe the trends would gradually increase due to the fact that we have a pandemic, so investors would pay close attention before executing a Buy. I would buy this stock, it’s the healthcare industry that’s attracting investors. In the end, that’s my take on LLY.

**Comment by hs115488** [comment]
So where are the sales of these prescription drugs within your report? Where is also the flow of the business capital and how is it distributed between the product and expenses? But explain why it's a great buy? Not if it is a good buy? Most pharmaceutical companies crash after 1 year. What makes this one different? Your report decides whether billions of your company's money goes into buying that stock. Don't get fired off of assuming the stock will go up.
